SPEC_WORD_PAIRS = [('ä','a'),('ã','a'),('á','a'),('â','a'),('ç','c'),('đ','d'),('ð','d'),('é','e'),('ê','e'),('ë','e'),('ı','i'),('í','i'),('ł','l'),('ñ','n'),('π','n'),('ö','o'),('ó','o'),('ø','o'),('ü','u'),('ú','u'),('ý','y'),('ξ','')]

STOPWORDS = {'jr','iii','dr','mr','junior'}

NICKNAME_DICT = {
    "al": "albert",
    "andy": "andrew",
    "tony": "anthony",
    "art": "arthur",
    "arty": "arthur",
    "bernie": "bernard",
    "bern": "bernard",
    "charlie": "charles",
    "chuck": "charles",
    "danny": "daniel",
    "dan": "daniel",
    "don": "donald",
    "ed": "edward",
    "eddie": "edward",
    "gene": "eugene",
    "fran": "francis",
    "freddy": "frederick",
    "fred": "frederick",
    "hank": "henry",
    "irv": "irving",
    "jimmy": "james",
    "jim": "james",
    "joe": "joseph",
    "jacky": "john",
    "jack": "john",
    "jeff": "jeffrey",
    "ken": "kenneth",
    "larry": "lawrence",
    "leo": "leonard",
    "matt": "matthew",
    "mike": "michael",
    "nate": "nathan",
    "nat": "nathan",
    "nick": "nicholas",
    "pat": "patrick",
    "pete": "peter",
    "ray": "raymond",
    "dick": "richard",
    "rick": "richard",
    "bob: bobby: rob": "robert",
    "ron: ronny": "ronald",
    "russ": "russell",
    "sam: sammy": "samuel",
    "steve": "stephan",
    "stu": "stuart",
    "teddy": "theodore",
    "ted": "theodore",
    "tom": "thomas",
    "thom": "thomas",
    "tommy": "thomas",
    "timmy": "timothy",
    "tim": "timothy",
    "walt": "walter",
    "wally": "walter",
    "bill": "william",
    "billy": "william",
    "will": "william",
    "willy": "william",
    "mandy": "amanda",
    "cathy": "catherine",
    "cath": "catherine",
    "chris": "christopher",
    "chrissy": "christine",
    "cindy: cynth": "cynthia",
    "debbie": "deborah",
    "deb": "deborah",
    "betty": "elizabeth",
    "beth": "elizabeth",
    "liz": "elizabeth",
    "bess": "elizabeth",
    "flo": "florence",
    "francie": "frances",
    "fran": "frances",
    "jan": "janet",
    "kate": "katherine",
    "kathy": "katherine",
    "jan": "janice",
    "nan": "nancy",
    "pam": "pamela",
    "pat": "patricia",
    "bobbie": "roberta",
    "sophie": "sophia",
    "sue": "susan",
    "suzie": "susan",
    "terry": "teresa",
    "val": "valerie",
    "ronnie": "veronica",
    "vonna": "yvonne",
    "peggy": "margaret",
    "ted": "edward",
    "sally": "sarah",
    "harry": "henry",
}
